language: node_js
node_js:
- '6.2'
script:
- npm install cross-env -global
- npm install
- npm test
- npm run build
after_success:
- coveralls
notifications:
  slack: react-ui-kit-project:RdAykQ4ON1eXu4x1bV1rWTmG